@Test public void test_isIn_assertion_error_message(){
  assertThatExceptionOfType(AssertionError.class).isThrownBy(() -> assertThat(LocalDateTime.of(2000,1,5,3,0,5)).isIn(LocalDateTime.of(2012,1,1,3,3,3).toString())).withMessage(format("%nExpecting:%n <2000-01-05T03:00:05>%nto be in:%n <[2012-01-01T03:03:03]>%n"));
}
