@Test public void should_fail_if_suppressed_exception_has_different_type_and_message_to_expected_cause(){
  AssertionInfo info=someInfo();
  Throwable expectedSuppressedException=new NullPointerException("error cause");
  try {
    throwables.assertHasSuppressedException(info,throwableSuppressedException,expectedSuppressedException);
  }
 catch (  AssertionError err) {
    verify(failures).failure(info,shouldHaveSuppressedException(throwableSuppressedException,expectedSuppressedException));
    return;
  }
  failBecauseExpectedAssertionErrorWasNotThrown();
}
