/** 
 * Tests for <code> {@link Fail#shouldHaveThrown(Class)} (Class)}</code>.
 * @author Joel Costigliola
 */
public class Fail_fail_because_exception_was_not_thrown_Test {
  @Test public void should_include_message_built_with_given_exception_name(){
    assertThatExceptionOfType(AssertionError.class).isThrownBy(() -> failBecauseExceptionWasNotThrown(NullPointerException.class)).withMessage("NullPointerException should have been thrown");
  }
  @Test public void should_include_message_built_with_given_throwable_name(){
    assertThatExceptionOfType(AssertionError.class).isThrownBy(() -> failBecauseExceptionWasNotThrown(OutOfMemoryError.class)).withMessage("OutOfMemoryError should have been thrown");
  }
}
