@Test public void should_fail_if_completable_future_is_done(){
  CompletableFuture<String> future=CompletableFuture.completedFuture("done");
  assertThatThrownBy(() -> assertThat(future).isNotDone()).isInstanceOf(AssertionError.class).hasMessage(shouldNotBeDone(future).create());
}
