@Test public void testInvokeOccurResourcenotfoundexceptionInNestedMethod03() throws Throwable {
  ResourceNotFoundException occurException=new ResourceNotFoundException(ResultMessages.error().add("e.cm.xxx1","args1","args2"),null);
  TestService service=getApplicationContext().getBean(TestService.class);
  service.setResultMessagesNotificationException(occurException);
  try {
    TestFacade facade=getApplicationContext().getBean(TestFacade.class);
    facade.getMessage();
    fail("don't occur ResourceNotFoundException.");
  }
 catch (  ResourceNotFoundException e) {
    assertThat(e,is(occurException));
    verify(mockExceptionLogger,times(1)).warn(occurException);
    verify(mockExceptionLogger,times(1)).warn((Exception)anyObject());
  }
}
