@Test public void should_throw_PathsException_on_io_error() throws IOException {
  final IOException exception=new IOException();
  when(actual.toRealPath()).thenThrow(exception);
  assertThatExceptionOfType(PathsException.class).isThrownBy(() -> paths.assertIsCanonical(info,actual)).withMessage("failed to resolve actual real path").withCause(exception);
}
