@Test public void checkedPredicateCheckedException(){
  Verify.assertThrowsWithCause(RuntimeException.class,IOException.class,() -> {
    CheckedPredicate<String> block=new CheckedPredicate<String>(){
      @Override public boolean safeAccept(      String object) throws IOException {
        throw new IOException("fail");
      }
    }
;
    block.accept("1");
  }
);
}
