@Test public void catchThrowableOfType_should_fail_with_good_message_if_wrong_type(){
  try {
    catchThrowableOfType(raisingException("boom!!"),RuntimeException.class);
  }
 catch (  AssertionError e) {
    assertThat(e).hasMessageContaining(RuntimeException.class.getName()).hasMessageContaining(Exception.class.getName());
    return;
  }
  shouldHaveThrown(AssertionError.class);
}
