@Test public void noRecoveryFromInternalErrorWithRetryDisabled() throws Exception {
  noRecoveryFromErrorWithRetryDisabled(ErrorCode.INTERNAL_ERROR);
}
