@Test public void should_fail_when_predicate_does_not_accept_value(){
  IntPredicate predicate=val -> val <= 2;
  Predicate<Integer> wrapPredicate=predicate::test;
  int expectedValue=3;
  assertThatExceptionOfType(AssertionError.class).isThrownBy(() -> assertThat(predicate).accepts(expectedValue)).withMessage(shouldAccept(wrapPredicate,expectedValue,PredicateDescription.GIVEN).create());
}
